wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 80:80
  volumes:
    - /opt/docker-persistence/wordpress/www/html:/var/www/html

db:
  image: mariadb
  volumes:
    - /opt/docker-persistence/mariadb/data:/var/lib/mysql
    - /opt/docker-persistence/mariadb/conf.d:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: example

